BeanSceneApp/Controllers/ContactsController.cs
using BeanSceneApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BeanSceneApp.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            LinkedList<Contact> contacts = new LinkedList<Contact>();
            contacts.AddFirst(new Contact("123 Fake Street", "Faketown", "notreal@fakemail.com", "12345678"));
            contacts.AddLast(new Contact("1 First Avenue", "Metro City", "ckent@dailyplanet.com", "11943123"));
            contacts.AddLast(new Contact("2 Cassandra View", "Darktown", "casscain@oracle.com", "21211991"));
            contacts.AddLast(new Contact("21 Magic Lane", "Mas Vega", "zatannaz@magicmail.com", "00224375"));
            contacts.AddLast(new Contact("32 Astra Street", "Yao", "evelync@lyramail.com", "5555555"));
            return View(contacts);
        }
    }
}

BeanSceneApp/Controllers/GraphicsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Drawing;


namespace BeanSceneApp.Controllers
{
    public class GraphicsController : Controller
    {
        Pen pen;
        Brush brush;
        Brush brush2;
        Brush brush3;

        public GraphicsController()
        {
            pen = new Pen(Color.Black, 2);
            brush = new SolidBrush(Color.Blue);
            brush2 = new SolidBrush(Color.Aquamarine);
            brush3 = new SolidBrush(Color.Green);
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GenerateCircle()
        {
            int width = 200;
            int height = 200;
            using (var bitmap = new Bitmap(width, height))
            {
                using (var graphics = Graphics.FromImage(bitmap))
                {
                    //graphics.Clear(Color.White);
                    graphics.FillEllipse(brush, 0, 0, width, height);
                    graphics.DrawEllipse(pen, 0, 0, width, height);
                }
                using (MemoryStream ms = new MemoryStream())
                {
                    bitmap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                    ms.Seek(0, SeekOrigin.Begin);
                    return File(ms.ToArray(), "image/png");
                }
            }
        }
        public IActionResult GenerateRectangle()
        {
            int width = 200;
            int height = 200;
            using (var bitmap = new Bitmap(width, height))
            {
                using (var graphics = Graphics.FromImage(bitmap))
                {
                    graphics.Clear(Color.White);
                    graphics.FillRectangle(brush2, 0, 0, width, height);
                    graphics.DrawRectangle(pen, 0, 0, width, height);
                }
                using (MemoryStream ms = new MemoryStream())
                {
                    bitmap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                    ms.Seek(0, SeekOrigin.Begin);
                    return File(ms.ToArray(), "image/png");
                }
            }
        }
        public IActionResult GenerateTriangle()
        {
            int width = 200;
            int height = 200;
            using (var bitmap = new Bitmap(width, height))
            {
                using (var graphics = Graphics.FromImage(bitmap))
                {
                   // graphics.Clear(Color.);
                    Point[] points = new Point[]
                    {
                        new Point(0, 0),
                        new Point(width, 0),
                        new Point(width/2, height),
                    };
                    graphics.FillPolygon(brush3, points);
                    graphics.DrawPolygon(pen, points);
                }
                using (MemoryStream ms = new MemoryStream())
                {
                    bitmap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                    ms.Seek(0, SeekOrigin.Begin);
                    return File(ms.ToArray(), "image/png");
                }
            }

        }
    }
}

BeanSceneApp/Controllers/UserController.cs
using BeanSceneApp.Models;
using BeanSceneApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

[Authorize(Roles = "Admin")]
public class UserController : Controller
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;


    public UserController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
    {
        _userManager = userManager;
        _roleManager = roleManager;
    }

    public async Task<IActionResult> Index()
    {
        var users = await _userManager.Users.ToListAsync();
        var userRolesViewModel = new List<UserRolesViewModel>();

        foreach (var user in users)
        {
            var thisViewModel = new UserRolesViewModel();
            thisViewModel.UserId = user.Id;
            thisViewModel.Email = user.Email;
            thisViewModel.Roles = await GetUserRoles(user);
            userRolesViewModel.Add(thisViewModel);
        }

        return View(userRolesViewModel);
    }

    private async Task<List<string>> GetUserRoles(IdentityUser user)
    {
        return new List<string>(await _userManager.GetRolesAsync(user));
    }

    public async Task<IActionResult> Manage(string userId)
    {
        ViewBag.userId = userId;
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null)
        {
            ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
            return View("NotFound");
        }

        ViewBag.UserName = user.UserName;
        var model = new List<ManageUserRolesViewModel>();

        foreach (var role in await _roleManager.Roles.ToListAsync())
        {
            var userRolesViewModel = new ManageUserRolesViewModel
            {
                RoleId = role.Id,
                RoleName = role.Name
            };

            if (await _userManager.IsInRoleAsync(user, role.Name))
            {
                userRolesViewModel.Selected = true;
            }
            else
            {
                userRolesViewModel.Selected = false;
            }

            model.Add(userRolesViewModel);
        }

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
    {
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null)
        {
            return View();
        }

        var roles = await _userManager.GetRolesAsync(user);
        var result = await _userManager.RemoveFromRolesAsync(user, roles);

        if (!result.Succeeded)
        {
            ModelState.AddModelError("", "Cannot remove user existing roles");
            return View(model);
        }

        result = await _userManager.AddToRolesAsync(user,
            model.Where(x => x.Selected).Select(y => y.RoleName));

        if (!result.Succeeded)
        {
            ModelState.AddModelError("", "Cannot add selected roles to user");
            return View(model);
        }
        EmailOuterService Outer = new EmailOuterService();

        return RedirectToAction("Index");
    }
}

BeanSceneApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeanSceneApp.Data;
using BeanSceneApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace BeanSceneApp.Controllers
{
    [Authorize(Roles = "Admin, Manager, Staff")]
    public class UsersController : Controller
    {
        private readonly BeanSceneAppContext _context;

        public UsersController(BeanSceneAppContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        [Authorize(Roles = "Admin, Staff")]
        // GET: Users/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(User user, IFormFile Image)
        {
            //[Bind("UserId,FirstName,LastName,Email,Phone,Password,Image,Role")]
            User user1 = new User();
            user1.FirstName = user.FirstName;
            user1.LastName = user.LastName;
            user1.Email = user.Email;
            user1.Phone = user.Phone;
            user1.Password = user.Password;
            user1.Role = user.Role;

            if (Image != null && Image.Length > 0)
            {
                var fileName = Path.GetFileName(Image.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
                if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images")))
                {
                    Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images"));
                }
                // Check if the file already exists, upload it only if it doesn't exist
                if (!System.IO.File.Exists(filePath))
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await Image.CopyToAsync(stream);
                        ViewBag.Message = "File uploaded successfully.";
                    }
                }
                else
                {
                    ViewBag.Message = "File already exists. Please choose a different file.";
                }
                user1.Image = "/images/" + fileName;
            }

            if (ModelState.IsValid)
            {
                _context.Add(user1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, User user, IFormFile Image)
        {
            //[Bind("UserId,FirstName,LastName,Email,Phone,Password,Image,Role")]
            User user1 = new User();
            if (id != user.UserId)
            {
                return NotFound();
            }
            else
            {
                user1.UserId = user.UserId;
                user1.FirstName = user.FirstName;
                user1.LastName = user.LastName;
                user1.Email = user.Email;
                user1.Phone = user.Phone;
                user1.Password = user.Password;
                user1.Role = user.Role;

                if (Image != null && Image.Length > 0)
                {
                    var fileName = Path.GetFileName(Image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
                    if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images")))
                    {
                        Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images"));
                    }
                    // Check if the file already exists, upload it only if it doesn't exist
                    if (!System.IO.File.Exists(filePath))
                    {
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await Image.CopyToAsync(stream);
                            ViewBag.Message = "File uploaded successfully.";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "File already exists. Please choose a different file.";
                    }
                    user1.Image = "/images/" + fileName;
                }
            }
        
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user1.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user1);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            if (user != null)
            {
                _context.User.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.UserId == id);
        }
    }
}

BeanSceneApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeanSceneApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BeanSceneApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.12.1/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
        @*     <div class="container-fluid"> *@
        @*         <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeanSceneApp</a> *@
        @*         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
        @*                 aria-expanded="false" aria-label="Toggle navigation"> *@
        @*             <span class="navbar-toggler-icon"></span> *@
        @*         </button> *@
        @*         <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> *@
        @*             <ul class="navbar-nav flex-grow-1"> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservation</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">User</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Sittings" asp-action="Index">Sitting</a> *@
        @*                 </li> *@
        @*             </ul> *@
        @*         </div> *@
        @*     </div> *@
        @* </nav> *@
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @* <li class="nav-item"> *@
                        @*     <a class="nav-link" asp-area="" asp-controller="Reservations" asp-action="Index">Reservation</a> *@
                        @* </li> *@
                        <li class="nav-item dropdown">
                            <a class="nav-link text-white-50 dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reservations</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Reservations" asp-action="Index">View Reservations</a>
                                <a class="dropdown-item" asp-controller="Reservations" asp-action="Create">Create Reservations</a>
                            </div>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Sittings" asp-action="Index">Sitting</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-white-50 dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">VIPs</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Users" asp-action="Index">View VIPs</a>
                                <a class="dropdown-item" asp-controller="Users" asp-action="Create">Create VIPs</a> 
                                 <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a> 
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Graphics" asp-action="Index">Kids Zone</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">User Management</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - BeanSceneApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>